/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Penyakit;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static model.Penyakit.viewTampilanSemua;
import model.DataPasien;


/**
 *
 * @author LENOVO
 */
public class MenuSortingPelayanan extends javax.swing.JFrame {

    /**
     * Creates new form MenuSortingPelayanan
     */
    public MenuSortingPelayanan() {
        initComponents();
        setSize(815, 540);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        loadTableData();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Kategori = new javax.swing.JComboBox<>();
        Cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpenyakit = new javax.swing.JTable();
        kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Sedang", "Gawat Darurat" }));
        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });
        jPanel1.add(Kategori);
        Kategori.setBounds(230, 140, 128, 22);

        Cari.setBackground(new java.awt.Color(153, 204, 255));
        Cari.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        Cari.setForeground(new java.awt.Color(255, 255, 255));
        Cari.setText("CARI");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        jPanel1.add(Cari);
        Cari.setBounds(380, 140, 75, 22);

        tabelpenyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Penyakit", "Penyakit", "Urgensi Penyakit"
            }
        ));
        jScrollPane1.setViewportView(tabelpenyakit);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 220, 600, 200);

        kembali.setBackground(new java.awt.Color(153, 153, 153));
        kembali.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(10, 470, 90, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Menu Sorting Pelayanan.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        this.dispose();
        new Tampilan_Menu_Staff().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriActionPerformed

    private void loadTableData() {
        try {
            List<Penyakit> daftarPenyakit = Penyakit.viewTampilanSemua();

            DefaultTableModel tableModel = (DefaultTableModel) tabelpenyakit.getModel();

            tableModel.setRowCount(0);

            for (Penyakit penyakit : daftarPenyakit) {
                tableModel.addRow(new Object[]{
                        penyakit.getId_penyakit(),      
                        penyakit.getNama_penyakit(),    
                        penyakit.getKategori_urgensi()
//                        penyakit.getNama_pasien()       // Nama Pasien
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        String kategori = (String) Kategori.getSelectedItem();

        try {
            List<Penyakit> daftarPenyakit = Penyakit.getPenyakitByKategoriPenyakit(kategori);

            DefaultTableModel tableModel = (DefaultTableModel) tabelpenyakit.getModel();

            tableModel.setRowCount(0);

            for (Penyakit penyakit : daftarPenyakit) {
                tableModel.addRow(new Object[]{
                        penyakit.getId_penyakit(),       
                        penyakit.getNama_penyakit(),     
                        penyakit.getKategori_urgensi()   
                });
            }
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CariActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSortingPelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSortingPelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSortingPelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSortingPelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSortingPelayanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JComboBox<String> Kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTable tabelpenyakit;
    // End of variables declaration//GEN-END:variables
}
