/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Antrian;
import static model.Antrian.viewTampilanSemua;
import model.DataPasien;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author LENOVO
 */
public class Tampilan_Pasien_LihatAntrian extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_Pasien_LihatAntrian
     */
    public Tampilan_Pasien_LihatAntrian() {
        initComponents();
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JComboBox<>();
        caritext = new javax.swing.JTextField();
        caributton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableantrian = new javax.swing.JTable();
        kembalibutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cari");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 140, 69, 16);

        cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Pasien", "Nama Pasien" }));
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari);
        cari.setBounds(120, 140, 103, 22);

        caritext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caritextActionPerformed(evt);
            }
        });
        jPanel1.add(caritext);
        caritext.setBounds(270, 140, 287, 22);

        caributton.setBackground(new java.awt.Color(153, 204, 255));
        caributton.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        caributton.setForeground(new java.awt.Color(255, 255, 255));
        caributton.setText("CARI");
        caributton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caributtonActionPerformed(evt);
            }
        });
        jPanel1.add(caributton);
        caributton.setBounds(590, 140, 75, 23);

        tableantrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Antrian", "Waktu Masuk Antrian", "Status Antrian", "Nama Pasien"
            }
        ));
        jScrollPane1.setViewportView(tableantrian);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 170, 650, 240);

        kembalibutton.setBackground(new java.awt.Color(153, 153, 153));
        kembalibutton.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        kembalibutton.setForeground(new java.awt.Color(255, 255, 255));
        kembalibutton.setText("KEMBALI");
        kembalibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibuttonActionPerformed(evt);
            }
        });
        jPanel1.add(kembalibutton);
        kembalibutton.setBounds(621, 420, 90, 22);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(720, 170, 20, 240);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lihat antrian.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caritextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caritextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caritextActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void loadTableData() {
        try {
            List<Antrian> daftarAntrian = viewTampilanSemua();

            DefaultTableModel tableModel = (DefaultTableModel) tableantrian.getModel();

            tableModel.setRowCount(0);

            for (Antrian antrian : daftarAntrian) {
                tableModel.addRow(new Object[]{
                        antrian.getIdAntrian(),
                        antrian.getWaktuMasuk(),
                        antrian.getStatus(),
                        antrian.getIdPasien(),
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    private void caributtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caributtonActionPerformed
        String keyword = caritext.getText();
        String pilihan = (String) cari.getSelectedItem();

        DefaultTableModel model = (DefaultTableModel) tableantrian.getModel();
        model.setRowCount(0); 
        try {
            List<Antrian> dataPasienList;

            if (pilihan.equals("ID Pasien")) {
        model.setColumnIdentifiers(new Object[]{"ID Antrian", "Waktu Masuk", "Status", "Nama Pasien"});

        dataPasienList = Antrian.cariById(keyword);
        for (Antrian pasien : dataPasienList) {
            Object[] row = {
                pasien.getIdAntrian(),
                pasien.getWaktuMasuk(),
                pasien.getStatus(),
                pasien.getIdPasien(),
            };
            model.addRow(row);
        }
    } else if (pilihan.equals("Nama Pasien")) {
        model.setColumnIdentifiers(new Object[]{"ID Antrian", "Waktu Masuk", "Status", "ID Pasien"});

        dataPasienList = Antrian.cariByNama(keyword);
        for (Antrian pasien : dataPasienList) {
            Object[] row = {
                pasien.getIdAntrian(),
                pasien.getWaktuMasuk(),
                pasien.getStatus(),
                pasien.getIdPasien(), 
            };
            model.addRow(row);
        }
    } else {
        model.setColumnIdentifiers(new Object[]{"ID Antrian", "Waktu Masuk", "Status", "Detail"});
        dataPasienList = new ArrayList<>();
    }


            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_caributtonActionPerformed

    private void kembalibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibuttonActionPerformed
        this.dispose(); 
        new Tampilan_Menu_Pasien().setVisible(true); 
    }//GEN-LAST:event_kembalibuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Pasien_LihatAntrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cari;
    private javax.swing.JButton caributton;
    private javax.swing.JTextField caritext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembalibutton;
    private javax.swing.JTable tableantrian;
    // End of variables declaration//GEN-END:variables
}
