/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class Tampilan_Menu_Pasien extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_Menu_Pasien
     */
    public Tampilan_Menu_Pasien() {
        initComponents();
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpelayanpasien = new javax.swing.JButton();
        buatantrian = new javax.swing.JButton();
        lihatantrian = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jpelayanpasien.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jpelayanpasien.setForeground(new java.awt.Color(51, 153, 255));
        jpelayanpasien.setText("JADWAL PELAYANAN PASIEN");
        jpelayanpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpelayanpasienActionPerformed(evt);
            }
        });
        jPanel2.add(jpelayanpasien);
        jpelayanpasien.setBounds(280, 310, 240, 90);

        buatantrian.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        buatantrian.setForeground(new java.awt.Color(51, 153, 255));
        buatantrian.setText("BUAT ANTRIAN");
        buatantrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatantrianActionPerformed(evt);
            }
        });
        jPanel2.add(buatantrian);
        buatantrian.setBounds(140, 200, 190, 90);

        lihatantrian.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lihatantrian.setForeground(new java.awt.Color(51, 153, 255));
        lihatantrian.setText("LIHAT ANTRIAN");
        lihatantrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatantrianActionPerformed(evt);
            }
        });
        jPanel2.add(lihatantrian);
        lihatantrian.setBounds(480, 200, 200, 90);

        keluar.setBackground(new java.awt.Color(153, 153, 153));
        keluar.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel2.add(keluar);
        keluar.setBounds(620, 410, 80, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true); // Tampilkan tampilan login
            this.dispose(); // Tutup tampilan saat ini
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void jpelayanpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpelayanpasienActionPerformed
        new Tampilan_Pasien_LihatJadwalPelayanan().setVisible(true); // Navigasi ke jadwal pelayanan pasien
        this.dispose();
    }//GEN-LAST:event_jpelayanpasienActionPerformed

    private void buatantrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatantrianActionPerformed
        new Tampilan_Pasien_BuatAntrian().setVisible(true); // Navigasi ke form buat antrian
        this.dispose();
    }//GEN-LAST:event_buatantrianActionPerformed

    private void lihatantrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatantrianActionPerformed
        new Tampilan_Pasien_LihatAntrian().setVisible(true); // Navigasi ke form lihat antrian
        this.dispose();
    }//GEN-LAST:event_lihatantrianActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Menu_Pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatantrian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jpelayanpasien;
    private javax.swing.JButton keluar;
    private javax.swing.JButton lihatantrian;
    // End of variables declaration//GEN-END:variables
}
