/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.DDokter;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author Acer GK
 */
public class Tampilan_Staff_Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_Staff
     */
    public Tampilan_Staff_Dokter() {
        initComponents();
        setSize(1045, 455);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        iddokter = new javax.swing.JTextField();
        notelepon = new javax.swing.JTextField();
        namadokter = new javax.swing.JTextField();
        jadwal = new javax.swing.JTextField();
        spesialisasidokter = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableupdate = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(362, 41, 0, 0);

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel4.setText("ID Dokter                  ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 50, 143, 19);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel1.setText("Jadwal Kerja ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 110, 126, 19);

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel6.setText("Nama Dokter            ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 100, 163, 19);

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel7.setText("Spesialisasi                ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 150, 143, 19);

        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel9.setText("No Telepon   ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(620, 60, 94, 19);
        getContentPane().add(iddokter);
        iddokter.setBounds(70, 70, 310, 22);
        getContentPane().add(notelepon);
        notelepon.setBounds(620, 80, 300, 22);

        namadokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namadokterActionPerformed(evt);
            }
        });
        getContentPane().add(namadokter);
        namadokter.setBounds(70, 120, 310, 22);

        jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalActionPerformed(evt);
            }
        });
        getContentPane().add(jadwal);
        jadwal.setBounds(620, 130, 300, 22);

        spesialisasidokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesialisasidokterActionPerformed(evt);
            }
        });
        getContentPane().add(spesialisasidokter);
        spesialisasidokter.setBounds(70, 170, 310, 22);

        hapus.setBackground(new java.awt.Color(153, 204, 255));
        hapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("DELETE");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(770, 160, 90, 39);

        keluar.setBackground(new java.awt.Color(153, 204, 255));
        keluar.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(890, 160, 90, 39);

        tambah.setBackground(new java.awt.Color(153, 204, 255));
        tambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("ADD");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(530, 160, 90, 39);

        update.setBackground(new java.awt.Color(153, 204, 255));
        update.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(650, 160, 90, 39);

        jTableupdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama Dokter", "Spesialisasi", "No Telepon", "Jadwal Kerja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableupdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableupdate);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(-20, 210, 1050, 205);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1010, 210, 20, 200);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Dokter.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spesialisasidokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesialisasidokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spesialisasidokterActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String id = iddokter.getText();
        String nama = namadokter.getText();
        String spesialisasi = spesialisasidokter.getText();
        String telepon = notelepon.getText();
        String jadwalKerja = jadwal.getText();
        String idPelayanan = null; 

        if (id.isEmpty() || nama.isEmpty() || spesialisasi.isEmpty() || telepon.isEmpty() || jadwalKerja.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DDokter dokter = new DDokter(id, nama, spesialisasi, telepon, jadwalKerja, idPelayanan);

        try {
            dokter.simpan();
            JOptionPane.showMessageDialog(this, "Data dokter berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadTableData(); 
            resetform(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }    
    private void resetform() {
        iddokter.setText("");
        namadokter.setText("");
        spesialisasidokter.setText("");
        notelepon.setText("");
        jadwal.setText("");
    }//GEN-LAST:event_tambahActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String id = iddokter.getText();
        String nama = namadokter.getText();
        String spesialisasi = spesialisasidokter.getText();
        String telepon = notelepon.getText();
        String jadwalKerja = jadwal.getText();
        String idPelayanan = null;

        DDokter dokter = new DDokter(id, nama, spesialisasi, telepon, jadwalKerja, idPelayanan);
        dokter.perbarui();
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String id = iddokter.getText();
        DDokter dokter = new DDokter(id, null, null, null, null, null);
        dokter.hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
        new Tampilan_Menu_Staff().setVisible(true);
    }//GEN-LAST:event_keluarActionPerformed

    private void namadokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namadokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namadokterActionPerformed

    private void loadTableData() {
        try {
            List<DDokter> daftarDokter = DDokter.viewTampilanSemua();

            DefaultTableModel tableModel = (DefaultTableModel) jTableupdate.getModel();

            tableModel.setRowCount(0);

            for (DDokter dokter : daftarDokter) {
                tableModel.addRow(new Object[]{
                        dokter.getIdDokter(),        
                        dokter.getNamaDokter(),      
                        dokter.getSpesialisasi(),    
                        dokter.getTelepon(),        
                        dokter.getJadwalKerja(),     
                        dokter.getIdPelayanan()      
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalActionPerformed

    private void jTableupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableupdateMouseClicked
        int selectedRow = jTableupdate.getSelectedRow(); 
    
        if (selectedRow >= 0) { 
            DefaultTableModel tableModel = (DefaultTableModel) jTableupdate.getModel();

            iddokter.setText(tableModel.getValueAt(selectedRow, 0).toString());       
            namadokter.setText(tableModel.getValueAt(selectedRow, 1).toString());    
            spesialisasidokter.setText(tableModel.getValueAt(selectedRow, 2).toString()); 
            notelepon.setText(tableModel.getValueAt(selectedRow, 3).toString());     
            jadwal.setText(tableModel.getValueAt(selectedRow, 4).toString());        
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada baris yang dipilih!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableupdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Staff_Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JTextField iddokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableupdate;
    private javax.swing.JTextField jadwal;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField namadokter;
    private javax.swing.JTextField notelepon;
    private javax.swing.JTextField spesialisasidokter;
    private javax.swing.JButton tambah;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
