/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.DataPasien;
 /*
 * @author LENOVO
 */
public class Tampilan_Pasien_BuatAntrian extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_Pasien_BuatAntrian
     */
    public Tampilan_Pasien_BuatAntrian() {
        initComponents();
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_pasien = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        nomor_bpjs = new javax.swing.JTextField();
        nomor_telepon = new javax.swing.JTextField();
        combo_status = new javax.swing.JComboBox<>();
        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel1.setText("ID Pasien");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 140, 69, 19);

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel2.setText("Nama Antrian");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 180, 90, 19);

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel3.setText("Nomor BPJS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 220, 85, 19);

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel4.setText("Nomor Telepon");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 270, 100, 19);

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel5.setText("Status Antrian");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 320, 90, 19);

        id_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pasienActionPerformed(evt);
            }
        });
        jPanel1.add(id_pasien);
        id_pasien.setBounds(160, 140, 200, 22);

        nama_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pasienActionPerformed(evt);
            }
        });
        jPanel1.add(nama_pasien);
        nama_pasien.setBounds(160, 180, 200, 22);

        nomor_bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomor_bpjsActionPerformed(evt);
            }
        });
        jPanel1.add(nomor_bpjs);
        nomor_bpjs.setBounds(160, 220, 200, 22);

        nomor_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomor_teleponActionPerformed(evt);
            }
        });
        jPanel1.add(nomor_telepon);
        nomor_telepon.setBounds(160, 270, 200, 22);

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Dalam Antrian", "Selesai" }));
        combo_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_statusActionPerformed(evt);
            }
        });
        jPanel1.add(combo_status);
        combo_status.setBounds(160, 320, 110, 22);

        batal.setBackground(new java.awt.Color(153, 153, 153));
        batal.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        batal.setForeground(new java.awt.Color(255, 255, 255));
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal);
        batal.setBounds(70, 390, 109, 40);

        simpan.setBackground(new java.awt.Color(153, 204, 255));
        simpan.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(230, 390, 109, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Daftar Pasien.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        new Tampilan_Menu_Pasien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void id_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pasienActionPerformed

    private void nama_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pasienActionPerformed

    private void nomor_bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomor_bpjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomor_bpjsActionPerformed

    private void nomor_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomor_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomor_teleponActionPerformed

    private void combo_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_statusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            // Ambil data dari form
            String idPasien = id_pasien.getText();
            String namaPasien = nama_pasien.getText();
            String nomorBPJS = nomor_bpjs.getText();
            String nomorTelepon = nomor_telepon.getText();
            String statusAntrian = (String) combo_status.getSelectedItem();
            String idPenyakit = null; // Jika Anda memiliki input untuk penyakit, tambahkan di sini

            // Validasi input
            if (idPasien.isEmpty() || namaPasien.isEmpty() || nomorTelepon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mohon isi semua data yang diperlukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Buat objek DataPasien
            DataPasien dataPasien = new DataPasien(idPasien, namaPasien, nomorBPJS, nomorTelepon, statusAntrian, idPenyakit);

            // Simpan ke database
            dataPasien.simpan();

            // Notifikasi sukses
            JOptionPane.showMessageDialog(this, "Data pasien berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Reset form setelah data disimpan
            resetForm();
        } catch (Exception e) {
            // Tangani error
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // Metode untuk mereset form
    private void resetForm() {
        id_pasien.setText("");
        nama_pasien.setText("");
        nomor_bpjs.setText("");
        nomor_telepon.setText("");
        combo_status.setSelectedIndex(0);
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_BuatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_BuatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_BuatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Pasien_BuatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Pasien_BuatAntrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JTextField id_pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField nomor_bpjs;
    private javax.swing.JTextField nomor_telepon;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
