/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Tampilan_Menu_Staff extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_User_Menu
     */
    public Tampilan_Menu_Staff() {
        initComponents();
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dokter = new javax.swing.JButton();
        pelayanan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        dataantrian = new javax.swing.JButton();
        SortingPenyakit = new javax.swing.JButton();
        menupelayanan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        dokter.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        dokter.setForeground(new java.awt.Color(102, 153, 255));
        dokter.setText("Data Dokter");
        dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterActionPerformed(evt);
            }
        });
        jPanel1.add(dokter);
        dokter.setBounds(310, 190, 170, 90);

        pelayanan.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        pelayanan.setForeground(new java.awt.Color(102, 153, 255));
        pelayanan.setText("Data Pasien");
        pelayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayananActionPerformed(evt);
            }
        });
        jPanel1.add(pelayanan);
        pelayanan.setBounds(90, 190, 170, 90);

        keluar.setBackground(new java.awt.Color(153, 153, 153));
        keluar.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(624, 400, 80, 22);

        dataantrian.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        dataantrian.setForeground(new java.awt.Color(102, 153, 255));
        dataantrian.setText("Data Antrian");
        dataantrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataantrianActionPerformed(evt);
            }
        });
        jPanel1.add(dataantrian);
        dataantrian.setBounds(520, 190, 170, 90);

        SortingPenyakit.setFont(new java.awt.Font("Cooper Black", 1, 15)); // NOI18N
        SortingPenyakit.setForeground(new java.awt.Color(102, 153, 255));
        SortingPenyakit.setText("Sorting Penyakit");
        SortingPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortingPenyakitActionPerformed(evt);
            }
        });
        jPanel1.add(SortingPenyakit);
        SortingPenyakit.setBounds(190, 300, 170, 90);

        menupelayanan.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        menupelayanan.setForeground(new java.awt.Color(102, 153, 255));
        menupelayanan.setText("Pelayanan");
        menupelayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupelayananActionPerformed(evt);
            }
        });
        jPanel1.add(menupelayanan);
        menupelayanan.setBounds(420, 300, 170, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterActionPerformed
        new Tampilan_Staff_Dokter().setVisible(true); // Pastikan kelas ini tersedia
        this.dispose(); 
    }//GEN-LAST:event_dokterActionPerformed

    private void pelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayananActionPerformed
        new Tampilan_Staff_Pasien().setVisible(true); // Pastikan kelas ini tersedia
        this.dispose();
    }//GEN-LAST:event_pelayananActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true); // Kembali ke halaman login
            this.dispose(); // Tutup tampilan saat ini
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void SortingPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortingPenyakitActionPerformed
        new MenuSortingPelayanan().setVisible(true); // Pastikan kelas ini tersedia
        this.dispose();
    }//GEN-LAST:event_SortingPenyakitActionPerformed

    private void dataantrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataantrianActionPerformed
        new Tampilan_staff_DataAntrian().setVisible(true); // Pastikan kelas ini tersedia
        this.dispose();
    }//GEN-LAST:event_dataantrianActionPerformed

    private void menupelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupelayananActionPerformed
        new Tampilan_Staff_MenuPelayanan().setVisible(true); // Pastikan kelas ini tersedia
        this.dispose();
    }//GEN-LAST:event_menupelayananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Menu_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Menu_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SortingPenyakit;
    private javax.swing.JButton dataantrian;
    private javax.swing.JButton dokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton menupelayanan;
    private javax.swing.JButton pelayanan;
    // End of variables declaration//GEN-END:variables
}
