/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.DataPasien;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JFrame;
/**
 *
 * @author Acer GK
 */
public class Tampilan_Staff_Pasien extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_Staff
     */
    public Tampilan_Staff_Pasien() {
        initComponents();
        setSize(1045, 455);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableupdate = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        no_telepon = new javax.swing.JTextField();
        no_bpjs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Status_antrian = new javax.swing.JComboBox<>();
        nama_pasien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id_pasien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableupdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pasien", "Nama Pasien", "No BPJS", "Nomor Telepon", "Status Antrian"
            }
        ));
        jTableupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableupdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableupdate);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 1030, 205);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(358, 41, 0, 0);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        tambah.setBackground(new java.awt.Color(153, 204, 255));
        tambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("ADD");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel3.add(tambah);
        tambah.setBounds(540, 160, 90, 39);

        delete.setBackground(new java.awt.Color(153, 204, 255));
        delete.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(790, 160, 90, 39);

        update.setBackground(new java.awt.Color(153, 204, 255));
        update.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update);
        update.setBounds(670, 160, 90, 39);

        keluar.setBackground(new java.awt.Color(153, 204, 255));
        keluar.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel3.add(keluar);
        keluar.setBounds(910, 160, 86, 39);

        no_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_teleponActionPerformed(evt);
            }
        });
        jPanel3.add(no_telepon);
        no_telepon.setBounds(640, 80, 300, 22);

        no_bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_bpjsActionPerformed(evt);
            }
        });
        jPanel3.add(no_bpjs);
        no_bpjs.setBounds(50, 170, 300, 22);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel1.setText("Status Antrian");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(640, 110, 130, 19);

        Status_antrian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Sedang Diperiksa", "Selesai", " " }));
        Status_antrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status_antrianActionPerformed(evt);
            }
        });
        jPanel3.add(Status_antrian);
        Status_antrian.setBounds(640, 130, 300, 22);
        jPanel3.add(nama_pasien);
        nama_pasien.setBounds(50, 120, 300, 22);

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel6.setText("Nama Pasien             ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 100, 144, 19);
        jPanel3.add(id_pasien);
        id_pasien.setBounds(50, 70, 300, 22);

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel7.setText("No. BPJS                     ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 150, 144, 19);

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel4.setText("ID Pasien                   ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 50, 143, 19);

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel5.setText("No Telepon                ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(640, 60, 150, 19);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Pasien.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 0, 1030, 416);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1030, 210);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1010, 210, 20, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Status_antrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status_antrianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Status_antrianActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String idPasien = id_pasien.getText();
        String nama = nama_pasien.getText();
        String noBpjs = no_bpjs.getText();
        String telepon = no_telepon.getText();
        String statusAntrian = Status_antrian.getSelectedItem().toString();
        String idPenyakit = null; 

        if (idPasien.isEmpty() || nama.isEmpty() || noBpjs.isEmpty() || telepon.isEmpty() || statusAntrian.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DataPasien pasien = new DataPasien(idPasien, nama, noBpjs, telepon, statusAntrian, idPenyakit);

        try {
            pasien.simpan(); 
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadTableData(); 
            resetForm(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }  

    private void resetForm() {
        id_pasien.setText(""); 
        nama_pasien.setText(""); 
        no_bpjs.setText(""); 
        no_telepon.setText(""); 
        Status_antrian.setSelectedIndex(0); 
    }//GEN-LAST:event_tambahActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String idPasien = id_pasien.getText();
        String nama = nama_pasien.getText();
        String noBpjs = no_bpjs.getText();
        String telepon = no_telepon.getText();
        String statusAntrian = Status_antrian.getSelectedItem().toString();

        DataPasien pasien = new DataPasien(idPasien, nama, noBpjs, telepon, statusAntrian, null);

        try {
            pasien.perbarui();
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
            resetForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String idPasien = id_pasien.getText();

        DataPasien pasien = new DataPasien(idPasien, null, null, null, null, null);

        try {
            pasien.hapus();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadTableData(); 
            resetForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
        new Tampilan_Menu_Staff().setVisible(true);
    }//GEN-LAST:event_keluarActionPerformed

    private void loadTableData() {
    try {
        List<DataPasien> daftarPasien = DataPasien.viewTampilanSemua();

        DefaultTableModel tableModel = (DefaultTableModel) jTableupdate.getModel();

        tableModel.setRowCount(0);

        for (DataPasien pasien : daftarPasien) {
            tableModel.addRow(new Object[]{
                    pasien.getIdPasien(),
                    pasien.getNama(),
                    pasien.getNoBpjs(),
                    pasien.getTelepon(),
                    pasien.getStatusAntrian()
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void no_bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_bpjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_bpjsActionPerformed

    private void no_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_teleponActionPerformed

    private void jTableupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableupdateMouseClicked
        int selectedRow = jTableupdate.getSelectedRow(); 
    
        if (selectedRow >= 0) { 
            DefaultTableModel tableModel = (DefaultTableModel) jTableupdate.getModel();

            id_pasien.setText(tableModel.getValueAt(selectedRow, 0).toString()); 
            nama_pasien.setText(tableModel.getValueAt(selectedRow, 1).toString()); 
            no_bpjs.setText(tableModel.getValueAt(selectedRow, 2).toString()); 
            no_telepon.setText(tableModel.getValueAt(selectedRow, 3).toString()); 
            Status_antrian.setSelectedItem(tableModel.getValueAt(selectedRow, 4).toString()); 
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada baris yang dipilih!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableupdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Staff_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Staff_Pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Status_antrian;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id_pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableupdate;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField no_bpjs;
    private javax.swing.JTextField no_telepon;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JButton tambah;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
